$env:CF_API_TOKEN="CUSTOM-TOKEN-WITH-SCRIPT-WORKERS-AND-CLOUDFARE-PAGES"
$env:CF_ACCOUNT_ID="WHEN-U-LAUNCH-DASH"
$env:CF_PAGES_PROJECT_NAME="EXAMPLE-COFFY-I-LOVE-YOU"
$env:CF_DELETE_ALIASED_DEPLOYMENTS="true"
node manageDeployments.js